#!/bin/bash -e

# required: set our language
export OUR_LANG="$LANG"
# turns out this is best set to the same value as the host system's LANG
# however, if you need to overwrite it, you can do it e.g. like so:
# export OUR_LANG="de_DE.UTF-8"
# required: set tempdir (needs at least 15 GB free space)
export TEMPIMAGEDIRROOT="/tmp"

# optional: allow debugging via USB ethernet interface
export DEBUG_VIA_USBETH="false"
# required if DEBUG_VIA_USBETH is set to "true":
#   first three octets and netmask of the IP network
#   you want to expose on the USB ethernet interface
#   (pick a network range that is not reachable via
#   regular wired ethernet or wifi)
export FIRSTTHREEOCTETS="10.0.0"
export NETMASK="255.255.0.0"

# optional: allow debugging via SPI display
export DEBUG_VIA_SPI="false"

# optional: set huge console font for easier debugging from a distance
export DEBUG_HUGE_CONSOLE_FONT="false"

# optional: allow booting into ENV1 by pulling a GPIO pin to ground
# if you're looking at the GPIO pins with the two +5V lines in the
# top right, then:
#
# GPIO4  - the *third* pin from the top on the *left*, and a suitable
#          ground pin is the *fourth* pin from the top on the *right*.
# GPIO15 - fifth from the top on the right, suitable GND also fifth - on the left
# GPIO21 - bottom right, GND bottom left
#
# We suggest GPIO21 and the GND pin next to it, as they are the easiest to locate
# (Our default is "", and thus "disabled" - so you don't have to worry if you're 
# already using GPIO21 for something else and want to give this installer a try)
#export GPIO_FORCE_ENV1="21"
export GPIO_FORCE_ENV1=""

# optional: override the default value for rootfs and data partitions
# rootfs default is "8G", data default is "" (meaning "use all remaining space")
# you can use K,M,G,T as units, but do not use blanks between digits and units
# also, do not attempt to use decimal values or thousands separators 
# like 2.5G or 1,024M - this will fail and wreak havoc
#
# if you only have 16G total storage, it should be safe to reduce the rootfs
# size from 8G to 4G to make everything fit.
# it's possible to go as low as 1900M for 8GB of total storage, but this requires
# additional steps to shrink down the original image to less than 1900M.
# do not attempt to set a value below 2500M with a stock image.
# you have been warned.
# see detailed instructions in expert/CREATE-8G-IMAGE.md for detailed instructions.
#
# also, if you have issues writing the image e.g. to CM4 eMMC flash, try the following:
# use regular USB media and write the image to it, then run this script on that media
# as well, with OVERRIDE_ROOTFS_MAXSIZE and OVERRIDE_DATA_MAXSIZE set to values
# that do not exceed the size of your eMMC flash.
# use the following formula to calculate the proper settings:
# eMMC size = 1.5 GB + (3* OVERRIDE_ROOTFS_MAXSIZE) + OVERRIDE_DATA_MAXSIZE
# see detailed instructions in expert/COPY-STICK-TO-FLASH.md for detailed instructions.
#
#export OVERRIDE_ROOTFS_MAXSIZE="8G"
#export OVERRIDE_DATA_MAXSIZE=""
