#!/bin/bash -e

# this file gets sourced during the final installation

# set the two-letter uppercase country code so your accesspoint won't transmit on illegal frequencies
# "00" is the pseudocode for the lowest common denominator, and safe to use in all countries.
COUNTRY="00"

# set the default SSID for your accesspoint
SSID="rrpi-ap"

# set the default channel for your accesspoint
# if you did not set a real country code above, you are limited to 2.4GHz channels 1-11 (recommended: 1, 6, 11)
# with a real country code, you can also use 5GHz channels 36-48 (recommended: 36, 40, 44, 48) in most countries.
CHANNEL=1

# set the passphrase (in plaintext) for your accesspoint
PASSPHRASE=PassPhras3!
