#!/bin/bash -e

# this file gets sourced during the final installation, right before the paperless-ngx script gets executed

# leave this empty to autodetect and use the hostname provided by DNS/DHCP/whatever name resolution you have
PAPERLESS_HOSTNAME=""

# leave this empty to autodetect and use the system-wide time zone (recommended)
PAPERLESS_TZ=""

# set this to the TCP port you want to use for your paperless-ngx docker instance (default: 8000)
PAPERLESS_PORT=8000

# select the database backend. As per https://docs.paperless-ngx.com/setup/#less-powerful-devices, sqlite is recommended for the Pi
PAPERLESS_BACKEND="sqlite"

# select "yes" or "no" to enable/disable Apache TIKA. Defaults to "no".
PAPERLESS_TIKA="no"

# select the languages supported for OCR - use three-letter language codes and plus signs as separators.
PAPERLESS_OCR_LANGS="eng+deu+fra"

# set the username to be used for the paperless-ngx WebGUI
# it makes sense to set this equal to the "default user" of your Raspberry Pi OS installation (thus, by default, "pi"),
# but it is not a hard requirement
PAPERLESS_USERNAME="pi"

# set the password (in plaintext) to be used for the paperless-ngx WebGUI
# you may set this to a different password than the one you specified for your "default user" during Raspberry Pi OS installation
PAPERLESS_PASSWORD="L3tMeIn!"

# set the default filesystem UID for the default user (note that the "default user" equals to "pi" and UID equals to 1000)
PAPERLESS_USER_UID=1000

# set the default filesystem GID for the default user (note that the "default user" equals to "pi" and GID equals to 1000)
PAPERLESS_USER_GID=1000

# set the E-Mail address for the PAPERLESS_USERNAME account
PAPERLESS_EMAIL="pi@localhost"

# these paths define the default folders, which will be located under /data/ENV{2,3}/paperless-ngx/
PAPERLESS_TARGET_FOLDER="/target"
PAPERLESS_CONSUME_FOLDER="/consume"
PAPERLESS_MEDIA_FOLDER="/media"
PAPERLESS_DATA_FOLDER="/data"
# this folder only becomes relevant when you switch the database backend to postgres or mariadb
PAPERLESS_DATABASE_FOLDER="/db"
