#!/bin/bash -e

echo "Adding boot partition chooser (autoboot.txt) to first partition ..."
# add boot partition chooser config file

# optional header - only required for GPIO_FORCE_ENV1 mode
if [ -n "$GPIO_FORCE_ENV1" ] ; then
	cat >> $MOUNTPOINT/boot/firmware/autoboot.txt <<GPIODEFINE
# define GPIO as input, and activate the built-in pull-up resistor
gpio=${GPIO_FORCE_ENV1}=ip,pu

GPIODEFINE
fi

# this part is always required
# note that we need to start off with boot_partition=1
# or else our installation routines (in templates/autostart.sh) will fail
cat >> $MOUNTPOINT/boot/firmware/autoboot.txt <<AUTOBOOT
# Default
[default]
boot_partition=1
[all]
AUTOBOOT

# optional footer - only required for GPIO_FORCE_ENV1 mode
if [ -n "$GPIO_FORCE_ENV1" ] ; then
	cat >> $MOUNTPOINT/boot/firmware/autoboot.txt <<SETENV1BOOT

# Rescue Environment - booted when GPIO is connected to ground
[gpio${GPIO_FORCE_ENV1}=0]
boot_partition=1
[all]

SETENV1BOOT
fi
