#!/bin/bash -e

echo "Setting and generating locale ..."
# set and generate locale so the following update steps won't complain
sed -e 's/^en_GB/# en_GB/' \
    -e "s/^# $OUR_LANG/$OUR_LANG/" \
    -i $MOUNTPOINT/etc/locale.gen
sed -e 's/=en_GB.*$/='$OUR_LANG'/' -i $MOUNTPOINT/etc/locale.conf
chroot $MOUNTPOINT locale-gen
