#!/bin/bash -e

# create custom directory as well as wpa_supplicant.conf file from templates, if not already present
mkdir -p  ./custom/lan-to-upstream-wifi-bridge/{wpa_supplicant,dnsmasq.d,network} $MOUNTPOINT/root/lan-to-upstream-wifi-bridge/{dnsmasq.d,network}
if [ "$USE_NETWORK_MANAGER" == "false" ] ; then
	[ -s ./custom/lan-to-upstream-wifi-bridge/wpa_supplicant/wpa_supplicant.conf ] || cp ./templates/wpa_supplicant.conf.template ./custom/lan-to-upstream-wifi-bridge/wpa_supplicant/wpa_supplicant.conf
	[ -s ./custom/lan-to-upstream-wifi-bridge/network/interfaces ] || cp ./templates/interfaces.template ./custom/lan-to-upstream-wifi-bridge/network/interfaces
else
	mkdir -p  ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/pre-up $MOUNTPOINT/root/lan-to-upstream-wifi-bridge/network/dispatcher/pre-up
	[ -s ./custom/lan-to-upstream-wifi-bridge/network/interfaces ] || sed '/^allow-hotplug wlan0/,/^$/d' templates/interfaces.template > ./custom/lan-to-upstream-wifi-bridge/network/interfaces
	[ -s ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/99-post-up.sh ] || grep post-up templates/interfaces.template | sed -e 's/^.*post-up //' > ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/99-post-up.sh
	[ -s ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/99-post-up.sh ] || grep pre-up templates/interfaces.template | sed -e 's/^.*pre-up //' > ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/pre-up/99-pre-up.sh
	chmod 755 ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/99-post-up.sh ./custom/lan-to-upstream-wifi-bridge/network/dispatcher/pre-up/99-pre-up.sh 
fi
[ -s ./custom/lan-to-upstream-wifi-bridge/dnsmasq.d/br0.conf ] || cp ./templates/dnsmasq-br0.conf.template ./custom/lan-to-upstream-wifi-bridge/dnsmasq.d/br0.conf

# copy config files to root directory so we can retrieve them later
rsync -aP ./custom/lan-to-upstream-wifi-bridge/* $MOUNTPOINT/root/lan-to-upstream-wifi-bridge/
