#!/bin/bash -e

# create custom directory and copy conf file to destination
if [ -s ./base_install_branch_specific_custom.conf ] ; then
	rsync -aP ./base_install_branch_specific_custom.conf ./base_install_branch_specific.conf $MOUNTPOINT/root/euro-office/
else
	rsync -aP ./base_install_branch_specific.conf $MOUNTPOINT/root/euro-office/
fi
