#!/bin/bash -e

# inject autostart.sh
if ! [ -f ./custom/autostart.sh ] ; then
	echo "No autostart.sh file found, using template from template directory."
	cp ./templates/autostart.sh ./custom/
	AUTOSTART_NO_CUSTOM=true
fi

if ! [ -x ./custom/autostart.sh ] ; then
	echo "No executable autostart.sh file found, setting executable bit."
	chmod +x ./custom/autostart.sh
fi

if bash -n ./custom/autostart.sh ; then
	echo "A syntactically correct autostart.sh file has been detected. Injecting it into the data partition ..."
	rsync -aPvH ./custom/autostart.sh $MOUNTPOINT/autostart.sh 
	echo "Enforcing root:root ownership of autostart.sh ..."
	chown root:root $MOUNTPOINT/autostart.sh
elif ! bash -n ./custom/autostart.sh ; then
	echo "Syntax error in autostart.sh detected. Aborting."
	exit 1
fi

if [ -n "$AUTOSTART_NO_CUSTOM" ]; then
	rm ./custom/autostart.sh
fi

exit 0
